[build]
  publish = "dist/ecommerce-app"
  command = "ng build --prod"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server"
  status = 200

